name: weather_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.7
  intl: ^0.20.2
  geolocator: ^10.0.1
  weather: ^3.1.0
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

 
  assets:
    - .env
